### ISSUE TITLE
Output as esm format

### ISSUE THREAD

**Issue by egoist** [egoist/esmon#3]
low priority, as I don't personally use `type: 'module'` that much yet.

**Comment by eugene1g** [comment]
Be careful here - there are still fundamental issues with ESM in Node, such as -
* `__dirname` and`__filename` are undefined and have to be mocked.
* Importing dependencies that provide both ESM and CJS is unreliable, can result in two instances of the same lib at runtime, which can cause subtle bugs if the dependency keeps an internal state.
* Import filename must be full path to the file with the extension. A lot of CJS code relies on the convention of `index.js` (so that `require('./module') === require('./module/index.js')`), or CJS hooks for importing `.json` files etc.

These issues can be resolved, and each developer can make their app compatible with both ESM and CJS, but if this library chooses to output as ESM it will likely not work for a lot of existing code and slow down adoption.

**Comment by egoist** [comment]
@eugene1g yeah this will only be an option, not the default behavior.  ideally, it should output esm only when `type: 'module'` is present in `package.json`.

**Comment by egoist** [comment]
esm can be enabled in v2.0 via `--esm` flag.
